version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Dhaka"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    commit-message:
      prefix: "deps"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "Asia/Dhaka"
    open-pull-requests-limit: 5
    groups:
      codeql-version-suite:
        applies-to: version-updates
        patterns:
          - "github/codeql-action/*"
        update-types:
          - "major"
          - "minor"
          - "patch"

      codeql-security-suite:
        applies-to: security-updates
        patterns:
          - "github/codeql-action/*"

      other-actions-patch-minor:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "github/codeql-action/*"
        update-types:
          - "minor"
          - "patch"

    commit-message:
      prefix: "ci"
